Prevent Updates to Unchanged Location Records
seattleflu/id3c pull request #297
Opened 2022-04-04 23:31 UTC by bencap

This change compares incoming values with existing values in the `warehouse.location` table
to decide if there is a need to perform an update. Unnecessary updates add bloat to the
table, which this change will cut down on.

2022-04-04 23:32 UTC, bencap commented
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate non-sequential PK increments in warehouse tables (encounters, individuals)](https://trello.com/c/p7WNVOVI/1336-investigate-non-sequential-pk-increments-in-warehouse-tables-encounters-individuals)

2022-04-15 19:00 UTC, davereinhart requested changes

2022-04-15 19:00 UTC, davereinhart commented on lib/id3c/cli/command/etl/__init__.py
> +                (location.hierarchy) != (%(hierarchy)s) as data_changed
We'll want to cast the incoming value to `hstore` data type for the comparison. The extra parenthesis aren't necessary.

2022-05-16 16:50 UTC, davereinhart reviewed
~~@bencap I noticed some interesting behavior when testing with a FHIR bundle containing multiple encounters. An update on the location record (when data has changed) happens for every encounter. I suspect that's because the changes aren't committed until the entire bundle is processed, but I haven't confirmed that yet.~~ Disregard, appears be to specific to the process I was using to test it, subsequent tests look good.

2022-05-16 19:42 UTC, davereinhart approved these changes

2022-05-16 20:53 UTC, merged

2022-05-16 21:03 UTC, bencap commented
Deployed.